package com.yibs.advisor.service.performance;

import com.yibs.advisor.domain.course.Course;
import com.yibs.advisor.domain.performance.GradeRecord;
import com.yibs.advisor.domain.user.Student;
import com.yibs.advisor.dto.request.GradeSubmissionRequest;
import com.yibs.advisor.dto.response.GpaResponse;
import com.yibs.advisor.dto.response.GradeRecordResponse;
import com.yibs.advisor.dto.response.RankingResponse;
import com.yibs.advisor.exception.StudentNotFoundException;
import com.yibs.advisor.repository.CourseRepository;
import com.yibs.advisor.repository.GradeRecordRepository;
import com.yibs.advisor.repository.StudentRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.*;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class PerformanceServiceImpl implements IPerformanceService {

    private final GradeRecordRepository gradeRecordRepository;
    private final StudentRepository studentRepository;
    private final CourseRepository courseRepository;

    @Override
    @Transactional
    public GradeRecordResponse submitGrade(GradeSubmissionRequest request) {
        Student student = studentRepository.findById(request.getStudentId())
                .orElseThrow(() -> new StudentNotFoundException(request.getStudentId().toString()));
        Course course = courseRepository.findById(request.getCourseId())
                .orElseThrow(() -> new RuntimeException("Course not found: " + request.getCourseId()));

        GradeRecord record = GradeRecord.builder()
                .student(student)
                .course(course)
                .semester(request.getSemester())
                .academicYear(request.getAcademicYear())
                .attendancePct(BigDecimal.valueOf(request.getAttendancePct()))
                .assignmentScore(BigDecimal.valueOf(request.getAssignmentScore()))
                .projectScore(BigDecimal.valueOf(request.getProjectScore()))
                .testScore(BigDecimal.valueOf(request.getTestScore()))
                .examScore(BigDecimal.valueOf(request.getExamScore()))
                .build();

        record = gradeRecordRepository.save(record);

        // totalScore is generated by DB, re-fetch to get it
        record = gradeRecordRepository.findById(record.getId()).orElse(record);

        String gradeLetter = computeGradeLetter(record.getTotalScore());
        BigDecimal gradePoints = computeGradePoints(gradeLetter);
        record.setGradeLetter(gradeLetter);
        record.setGradePoints(gradePoints);
        record = gradeRecordRepository.save(record);

        return toGradeResponse(record);
    }

    @Override
    @Transactional(readOnly = true)
    public GpaResponse getStudentSummary(UUID studentId) {
        Student student = studentRepository.findById(studentId)
                .orElseThrow(() -> new StudentNotFoundException(studentId.toString()));

        List<GradeRecord> records = gradeRecordRepository.findByStudentId(studentId);

        // Compute GPA per semester using Streams
        Map<String, List<GradeRecord>> bySemester = records.stream()
                .filter(r -> r.getGradePoints() != null)
                .collect(Collectors.groupingBy(r -> r.getSemester() + "-" + r.getAcademicYear()));

        List<GpaResponse.SemesterGpa> semesterGpas = bySemester.entrySet().stream()
                .map(entry -> {
                    String[] parts = entry.getKey().split("-");
                    Short semester = Short.parseShort(parts[0]);
                    String academicYear = parts[1];
                    List<GradeRecord> semRecords = entry.getValue();

                    BigDecimal totalPoints = semRecords.stream()
                            .map(r -> r.getGradePoints().multiply(BigDecimal.valueOf(r.getCourse().getCreditHours())))
                            .reduce(BigDecimal.ZERO, BigDecimal::add);

                    int totalCredits = semRecords.stream()
                            .mapToInt(r -> r.getCourse().getCreditHours())
                            .sum();

                    BigDecimal gpa = totalCredits > 0
                            ? totalPoints.divide(BigDecimal.valueOf(totalCredits), 3, RoundingMode.HALF_UP)
                            : BigDecimal.ZERO;

                    return GpaResponse.SemesterGpa.builder()
                            .semester(semester)
                            .academicYear(academicYear)
                            .gpa(gpa)
                            .credits(totalCredits)
                            .build();
                })
                .sorted(Comparator.comparing(GpaResponse.SemesterGpa::getSemester))
                .toList();

        // Compute CGPA (cumulative)
        BigDecimal cumulativePoints = records.stream()
                .filter(r -> r.getGradePoints() != null)
                .map(r -> r.getGradePoints().multiply(BigDecimal.valueOf(r.getCourse().getCreditHours())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        int totalCredits = records.stream()
                .filter(r -> r.getGradePoints() != null)
                .mapToInt(r -> r.getCourse().getCreditHours())
                .sum();

        BigDecimal cgpa = totalCredits > 0
                ? cumulativePoints.divide(BigDecimal.valueOf(totalCredits), 3, RoundingMode.HALF_UP)
                : BigDecimal.ZERO;

        // Latest semester GPA
        BigDecimal latestGpa = semesterGpas.isEmpty() ? BigDecimal.ZERO
                : semesterGpas.get(semesterGpas.size() - 1).getGpa();

        return GpaResponse.builder()
                .studentId(studentId)
                .studentName(student.getFirstName() + " " + student.getLastName())
                .gpa(latestGpa)
                .cgpa(cgpa)
                .totalCredits(totalCredits)
                .completedCredits(totalCredits)
                .semesters(semesterGpas)
                .build();
    }

    @Override
    @Transactional(readOnly = true)
    public List<RankingResponse> getRanking(UUID courseId) {
        List<GradeRecord> records = courseId != null
                ? gradeRecordRepository.findByCourseId(courseId)
                : gradeRecordRepository.findAll();

        // Group by student, compute CGPA using Streams
        Map<UUID, List<GradeRecord>> byStudent = records.stream()
                .filter(r -> r.getGradePoints() != null)
                .collect(Collectors.groupingBy(r -> r.getStudent().getId()));

        List<RankingResponse> rankings = byStudent.entrySet().stream()
                .map(entry -> {
                    UUID studentId = entry.getKey();
                    List<GradeRecord> studentRecords = entry.getValue();

                    Student student = studentRecords.get(0).getStudent();

                    BigDecimal totalPoints = studentRecords.stream()
                            .map(r -> r.getGradePoints().multiply(BigDecimal.valueOf(r.getCourse().getCreditHours())))
                            .reduce(BigDecimal.ZERO, BigDecimal::add);

                    int totalCredits = studentRecords.stream()
                            .mapToInt(r -> r.getCourse().getCreditHours())
                            .sum();

                    BigDecimal cgpa = totalCredits > 0
                            ? totalPoints.divide(BigDecimal.valueOf(totalCredits), 3, RoundingMode.HALF_UP)
                            : BigDecimal.ZERO;

                    return RankingResponse.builder()
                            .studentId(studentId)
                            .studentName(student.getFirstName() + " " + student.getLastName())
                            .studentIdCode(student.getStudentId())
                            .cgpa(cgpa)
                            .creditsCompleted(totalCredits)
                            .build();
                })
                .sorted(Comparator.comparing(RankingResponse::getCgpa).reversed())
                .toList();

        // Assign ranks
        List<RankingResponse> ranked = new ArrayList<>();
        for (int i = 0; i < rankings.size(); i++) {
            RankingResponse r = rankings.get(i);
            r.setRank(i + 1);
            ranked.add(r);
        }

        return ranked;
    }

    private String computeGradeLetter(BigDecimal totalScore) {
        if (totalScore == null) return null;
        double score = totalScore.doubleValue();
        if (score >= 80) return "A";
        if (score >= 75) return "B+";
        if (score >= 70) return "B";
        if (score >= 65) return "C+";
        if (score >= 60) return "C";
        if (score >= 50) return "D";
        return "F";
    }

    private BigDecimal computeGradePoints(String gradeLetter) {
        if (gradeLetter == null) return null;
        return switch (gradeLetter) {
            case "A" -> BigDecimal.valueOf(4.0);
            case "B+" -> BigDecimal.valueOf(3.5);
            case "B" -> BigDecimal.valueOf(3.0);
            case "C+" -> BigDecimal.valueOf(2.5);
            case "C" -> BigDecimal.valueOf(2.0);
            case "D" -> BigDecimal.valueOf(1.0);
            default -> BigDecimal.ZERO;
        };
    }

    private GradeRecordResponse toGradeResponse(GradeRecord record) {
        return GradeRecordResponse.builder()
                .id(record.getId())
                .studentId(record.getStudent().getId())
                .courseId(record.getCourse().getId())
                .courseCode(record.getCourse().getCode())
                .courseName(record.getCourse().getTitle())
                .semester(record.getSemester())
                .academicYear(record.getAcademicYear())
                .attendancePct(record.getAttendancePct() != null ? record.getAttendancePct().doubleValue() : null)
                .assignmentScore(record.getAssignmentScore() != null ? record.getAssignmentScore().doubleValue() : null)
                .projectScore(record.getProjectScore() != null ? record.getProjectScore().doubleValue() : null)
                .testScore(record.getTestScore() != null ? record.getTestScore().doubleValue() : null)
                .examScore(record.getExamScore() != null ? record.getExamScore().doubleValue() : null)
                .totalScore(record.getTotalScore())
                .gradeLetter(record.getGradeLetter())
                .gradePoints(record.getGradePoints())
                .build();
    }
}
